name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-lb-service:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push lb-service
        uses: docker/build-push-action@v5
        with:
          context: ./load-balancer-service/
          file: ./load-balancer-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lb-service:latest
  build-backend-service:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push backend-service
        uses: docker/build-push-action@v5
        with:
          context: ./backend-service/
          file: ./backend-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-service:latest