name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Gradle-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build
  Docker-Build:
    environment: dev
    runs-on: ubuntu-latest
    needs: [Gradle-Build]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push lb-service
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:load-balancer-service"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lb-service:latest
      - name: Build and push backend-service
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:backend-service"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-service:latest
